spring:
  datasource:
    url: jdbc:mysql://frps.lucien.ink:13306/pasteme
    username: username
    password: password
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.pasteme.common.entity
logging:
  level:
    cn.pasteme.backend: debug